version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: registro_fotografico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    working_dir: /code/app
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/code/app
      - ./static:/code/staticfiles
      - ./media:/code/media
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - POSTGRES_DB=registro_fotografico
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

volumes:
  postgres_data: