version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: registro_fotografico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
      
  nginx:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/staticfiles
      - ./media:/code/media
    depends_on:
      - web

  web:
    build: .
    container_name: django_web
    working_dir: /code/app
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    volumes:
      - ./app:/code/app
      - ./static:/code/staticfiles
      - ./media:/code/media
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - POSTGRES_DB=registro_fotografico
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      # Configuración para aumentar el límite de tamaño de archivos a 50MB
      - DATA_UPLOAD_MAX_MEMORY_SIZE=52428800
      - FILE_UPLOAD_MAX_MEMORY_SIZE=52428800
      - MAX_UPLOAD_SIZE=52428800

volumes:
  postgres_data: