# Generated by Django 4.2.10 on 2025-06-09 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0012_alter_tipoformularioproyecto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Ítem')),
                ('semana_obs', models.CharField(max_length=20, verbose_name='Semana de Observación')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('punto_inspeccion', models.CharField(blank=True, choices=[('', '---------'), ('Almacenamiento de materiales', 'Almacenamiento de materiales'), ('Calibración de equipos', 'Calibración de equipos'), ('Ensayos y pruebas', 'Ensayos y pruebas'), ('Partidas de estructuras', 'Partidas de estructuras'), ('Partidas de arquitectura', 'Partidas de arquitectura'), ('Partidas de IISS', 'Partidas de IISS'), ('Partidas de IIEE', 'Partidas de IIEE'), ('Partidas de IIMM', 'Partidas de IIMM'), ('Gestión de calidad', 'Gestión de calidad'), ('Lecciones Aprendidas', 'Lecciones Aprendidas')], default='', help_text='Selecciona un punto de inspección de la lista', max_length=50, verbose_name='Punto de Inspección')),
                ('sub_clasificacion', models.CharField(blank=True, choices=[('', '---------'), ('Materiales expuestos', 'Materiales expuestos'), ('Ordenamiento de materiales', 'Ordenamiento de materiales'), ('Verificación de calibración', 'Verificación de calibración'), ('Requerimiento de pruebas', 'Requerimiento de pruebas'), ('Muro anclado', 'Muro anclado'), ('Acero', 'Acero'), ('Encofrado', 'Encofrado'), ('Concreto', 'Concreto'), ('Curado', 'Curado'), ('Empastado y/o Pintura', 'Empastado y/o Pintura'), ('Cerámico y/o Porcelanato', 'Cerámico y/o Porcelanato'), ('Recorrido de tuberías', 'Recorrido de tuberías'), ('Obstrucción de tuberías', 'Obstrucción de tuberías'), ('Pruebas y Funcionamiento', 'Pruebas y Funcionamiento'), ('Planos sin sello', 'Planos sin sello')], default='', help_text='Selecciona una sub clasificación de la lista', max_length=100, verbose_name='Sub Clasificación')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Observación')),
                ('nivel_riesgo', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=10, verbose_name='Nivel de Riesgo')),
                ('recomendacion', models.TextField(verbose_name='Recomendación para Levantamiento')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Atendido', 'Atendido'), ('Cerrado', 'Cerrado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('foto_1', models.ImageField(blank=True, null=True, upload_to='observaciones/calidad/', verbose_name='Fotografía 01')),
                ('foto_2', models.ImageField(blank=True, null=True, upload_to='observaciones/calidad/', verbose_name='Fotografía 02')),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Usuario responsable de realizar el levantamiento de esta observación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_calidad', to='reportes.proyecto')),
            ],
            options={
                'verbose_name': 'Observación de Calidad',
                'verbose_name_plural': 'Observaciones de Calidad',
                'ordering': ['proyecto', 'item'],
                'unique_together': {('proyecto', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ObservacionSeguridadSSOMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Ítem')),
                ('punto_inspeccion', models.CharField(choices=[('', '---------'), ('Trabajos civiles', 'Trabajos civiles'), ('Trabajos de excavación y/o movimiento de tierra', 'Trabajos de excavación y/o movimiento de tierra'), ('Trabajos eléctricos', 'Trabajos eléctricos'), ('Trabajos en altura', 'Trabajos en altura'), ('Acabados/Arquitectura', 'Acabados/Arquitectura'), ('Transporte y carga', 'Transporte y carga'), ('Trabajos sanitarios', 'Trabajos sanitarios'), ('Trabajos de izaje', 'Trabajos de izaje'), ('Gestión de seguridad', 'Gestión de seguridad'), ('Gestión ambiental', 'Gestión ambiental'), ('Otros-S', 'Otros-S')], default='', help_text='Seleccione el punto de inspección', max_length=100, verbose_name='Punto de Inspección')),
                ('subclasificacion', models.CharField(choices=[('', '---------'), ('Servicios de bienestar', 'Servicios de bienestar'), ('Organización de las áreas de trabajo', 'Organización de las áreas de trabajo'), ('Instalaciones eléctricas provisionales', 'Instalaciones eléctricas provisionales'), ('Accesos y vías de circulación', 'Accesos y vías de circulación'), ('Identificación de materiales', 'Identificación de materiales'), ('Señalización, orden y limpieza', 'Señalización, orden y limpieza'), ('Iluminación', 'Iluminación'), ('Segregación de residuos', 'Segregación de residuos'), ('Inspección de seguridad', 'Inspección de seguridad'), ('Equipos de respuesta a emergencia', 'Equipos de respuesta a emergencia'), ('Acto inseguro', 'Acto inseguro'), ('Condición insegura', 'Condición insegura'), ('Uso de EPPs', 'Uso de EPPs'), ('Documentación', 'Documentación'), ('Otros-S', 'Otros-S')], default='', help_text='Seleccione la subclasificación', max_length=100, verbose_name='Subclasificación')),
                ('tipo_observacion', models.CharField(choices=[('', '---------'), ('Condición Insegura', 'Condición Insegura'), ('Acto Inseguro', 'Acto Inseguro'), ('Incumplimiento de Norma', 'Incumplimiento de Norma'), ('Observación Preventiva', 'Observación Preventiva')], default='', help_text='Seleccione el tipo de observación de seguridad', max_length=50, verbose_name='Tipo de Observación')),
                ('area', models.CharField(choices=[('', '---------'), ('Área Administrativa', 'Área Administrativa'), ('Almacén', 'Almacén'), ('Taller', 'Taller'), ('Obra Civil', 'Obra Civil'), ('Instalaciones Eléctricas', 'Instalaciones Eléctricas'), ('Instalaciones Sanitarias', 'Instalaciones Sanitarias'), ('Áreas Comunes', 'Áreas Comunes')], default='', help_text='Seleccione el área donde se realizó la observación', max_length=50, verbose_name='Área')),
                ('semana_obs', models.CharField(max_length=20, verbose_name='Semana de Observación')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('accion_correctiva', models.TextField(verbose_name='Acción Correctiva Propuesta')),
                ('nivel_riesgo', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=10, verbose_name='Nivel de Riesgo')),
                ('fecha_compromiso', models.DateField(blank=True, null=True, verbose_name='Fecha de Compromiso')),
                ('foto_1', models.ImageField(blank=True, null=True, upload_to='observaciones/ssoma/', verbose_name='Fotografía 01')),
                ('foto_2', models.ImageField(blank=True, null=True, upload_to='observaciones/ssoma/', verbose_name='Fotografía 02')),
                ('semana_levantamiento', models.CharField(max_length=20, verbose_name='Semana de levantamiento')),
                ('fecha_levantamiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de levantamiento')),
                ('descripcion', models.TextField(verbose_name='Descripción del levantamiento')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='levantamientos/', verbose_name='Fotografía')),
                ('tiempo_levantamiento', models.DurationField(verbose_name='Tiempo de levantamiento')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('comentario_revisor', models.TextField(blank=True, verbose_name='Comentario del revisor')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levantamientos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Persona responsable de atender la observación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_ssoma_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levantamientos_realizados', to=settings.AUTH_USER_MODEL)),
                ('observacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='levantamiento', to='obervaciones.observacioncalidad')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_ssoma', to='reportes.proyecto')),
            ],
            options={
                'verbose_name': 'Levantamiento de Observación',
                'verbose_name_plural': 'Levantamientos de Observaciones',
                'ordering': ['-fecha_levantamiento'],
            },
        ),
    ]
