# Generated by Django 4.2.10 on 2025-06-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obervaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacionseguridadssoma',
            name='observacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levantamiento', to='obervaciones.observacioncalidad'),
        ),
    ]
