# Generated by Django 4.2.10 on 2025-06-12 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0012_alter_tipoformularioproyecto_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obervaciones', '0003_notificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observacionseguridadssoma',
            options={'ordering': ['-fecha', 'proyecto', 'item'], 'verbose_name': 'Control de Observaciones de Seguridad', 'verbose_name_plural': 'Control de Observaciones de Seguridad'},
        ),
        migrations.AlterField(
            model_name='observacionseguridadssoma',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='observacionseguridadssoma',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_ssoma_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observacionseguridadssoma',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='observacionseguridadssoma',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_ssoma_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observacionseguridadssoma',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción de la Observación'),
        ),
        migrations.AlterField(
            model_name='observacionseguridadssoma',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Atendido', 'Atendido'), ('Cerrado', 'Cerrado')], default='Pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterUniqueTogether(
            name='observacionseguridadssoma',
            unique_together={('proyecto', 'item')},
        ),
        migrations.CreateModel(
            name='LevantamientoSSOMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_levantamiento', models.CharField(max_length=20, verbose_name='Semana de levantamiento')),
                ('fecha_levantamiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de levantamiento')),
                ('descripcion', models.TextField(verbose_name='Descripción del levantamiento')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='levantamientos/', verbose_name='Fotografía')),
                ('tiempo_levantamiento', models.DurationField(verbose_name='Tiempo de levantamiento')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20, verbose_name='Estado de revisión')),
                ('comentario_revisor', models.TextField(blank=True, verbose_name='Comentario del revisor')),
                ('revisado_en', models.DateTimeField(blank=True, null=True, verbose_name='Revisado en')),
                ('observacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='levantamiento', to='obervaciones.observacionseguridadssoma')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levantamientos_ssoma_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Levantamiento de Observación (SSOMA)',
                'verbose_name_plural': 'Levantamientos de Observaciones (SSOMA)',
                'ordering': ['-fecha_levantamiento'],
            },
        ),
        migrations.CreateModel(
            name='LevantamientoObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_levantamiento', models.CharField(max_length=20, verbose_name='Semana de levantamiento')),
                ('fecha_levantamiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de levantamiento')),
                ('descripcion', models.TextField(verbose_name='Descripción del levantamiento')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='levantamientos/', verbose_name='Fotografía')),
                ('tiempo_levantamiento', models.DurationField(verbose_name='Tiempo de levantamiento')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20, verbose_name='Estado de revisión')),
                ('comentario_revisor', models.TextField(blank=True, verbose_name='Comentario del revisor')),
                ('revisado_en', models.DateTimeField(blank=True, null=True, verbose_name='Revisado en')),
                ('observacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='levantamiento', to='obervaciones.observacioncalidad')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levantamientos_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Levantamiento de Observación (Calidad)',
                'verbose_name_plural': 'Levantamientos de Observaciones (Calidad)',
                'ordering': ['-fecha_levantamiento'],
            },
        ),
        migrations.RemoveField(
            model_name='observacionseguridadssoma',
            name='comentario_revisor',
        ),
        migrations.RemoveField(
            model_name='observacionseguridadssoma',
            name='fecha_levantamiento',
        ),
        migrations.RemoveField(
            model_name='observacionseguridadssoma',
            name='fotografia',
        ),
        migrations.RemoveField(
            model_name='observacionseguridadssoma',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='observacionseguridadssoma',
            name='semana_levantamiento',
        ),
        migrations.RemoveField(
            model_name='observacionseguridadssoma',
            name='tiempo_levantamiento',
        ),
    ]
