# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations, models
import django.contrib.auth.models
import django.utils.timezone
import django.contrib.auth.validators

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(
                    max_length=150,
                    unique=True,
                    validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                    error_messages={'unique': 'A user with that username already exists.'},
                    verbose_name='username',
                )),
                ('first_name', models.CharField(max_length=150, blank=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, blank=True, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPER', 'Supervisor'), ('FOTO', 'Fotógrafo'), ('VISOR', 'Visor')], default='VISOR', max_length=5, verbose_name='Rol del usuario')),
                ('telefono', models.CharField(max_length=20, blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(
                    to='auth.Group',
                    related_name='usuario_groups',
                    related_query_name='usuario',
                    blank=True,
                    help_text='The groups this user belongs to.',
                    verbose_name='groups',
                )),
                ('user_permissions', models.ManyToManyField(
                    to='auth.Permission',
                    related_name='usuario_permissions',
                    related_query_name='usuario',
                    blank=True,
                    help_text='Specific permissions for this user.',
                    verbose_name='user permissions',
                )),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReporteFotografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=200, verbose_name='Proyecto')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('contratista', models.CharField(max_length=200, verbose_name='Contratista')),
                ('codigo_proyecto', models.CharField(max_length=50, verbose_name='Código del proyecto')),
                ('version_reporte', models.CharField(max_length=10, verbose_name='Versión del reporte')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('elaborado_por', models.CharField(max_length=100, verbose_name='Elaborado por')),
                ('revisado_por', models.CharField(max_length=100, verbose_name='Revisado por')),
                ('inicio_supervision', models.DateField(verbose_name='Inicio de la Supervisión')),
                ('mes_actual_obra', models.PositiveIntegerField(verbose_name='Mes Actual de Obra')),
                ('reporte_numero', models.PositiveIntegerField(verbose_name='Reporte N°')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos/', verbose_name='Fotografía')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('descripcion', models.CharField(max_length=200, blank=True, null=True, verbose_name='Descripción')),
                ('reporte', models.ForeignKey(on_delete=models.CASCADE, related_name='fotos', to='reportes.reportefotografico')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
