# Generated by Django 4.2.10 on 2025-05-19 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_usuario_email_alter_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuarios', models.ManyToManyField(related_name='proyectos', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios con acceso')),
            ],
        ),
        migrations.AlterField(
            model_name='reportefotografico',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='reportes.proyecto'),
        ),
    ]
