# Generated by Django 4.2.10 on 2025-05-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_proyecto_cliente_proyecto_codigo_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='inicio_supervision',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de la Supervisión'),
        ),
    ]
