# Generated by Django 4.2.10 on 2025-05-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_alter_proyecto_inicio_supervision'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/', verbose_name='Imagen del proyecto'),
        ),
    ]
