# Generated by Django 4.2.10 on 2025-05-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_proyecto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('EDITOR', 'Editor'), ('VISOR', 'Visor')], default='VISOR', max_length=6, verbose_name='Rol del usuario'),
        ),
    ]
