# Generated by Django 4.2.10 on 2025-05-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefotografico',
            name='tipo_formulario',
            field=models.CharField(choices=[('REPORTE FOTOGRÁFICO', 'REPORTE FOTOGRÁFICO'), ('REPORTE DIARIO', 'REPORTE DIARIO'), ('CONTROL DE OBS CALIDAD', 'CONTROL DE OBS CALIDAD'), ('CONTROL DE NC CALIDAD', 'CONTROL DE NC CALIDAD'), ('CONTROL DE NC SSOMA', 'CONTROL DE NC SSOMA'), ('CONTROL DE RFI', 'CONTROL DE RFI'), ('CONTROL DE ODC', 'CONTROL DE ODC'), ('CONTROL DE VALORIZACIONES', 'CONTROL DE VALORIZACIONES'), ('CONTROL DE DOSSIER', 'CONTROL DE DOSSIER'), ('CONTROL DE CARTAS', 'CONTROL DE CARTAS')], default='REPORTE FOTOGRÁFICO', max_length=32, verbose_name='Tipo de Formulario'),
        ),
    ]
