# Generated by Django 4.2.10 on 2025-06-14 03:16

from django.db import migrations, models
import reportes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0012_alter_tipoformularioproyecto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoreporte',
            name='imagen',
            field=models.ImageField(help_text='Tamaño máximo permitido: 50.0 MB', upload_to='fotos/', validators=[reportes.validators.validate_file_size], verbose_name='Fotografía'),
        ),
    ]
