# Generated by Django 4.2.10 on 2025-06-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0013_alter_fotoreporte_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoreporte',
            name='imagen',
            field=models.ImageField(help_text='Tamaño máximo permitido: 50 MB', upload_to='fotos/', verbose_name='Fotografía'),
        ),
    ]
